version: '3'
services:
  harley-ubuntu:
    image: "harleyliu/ubuntu:latest"
    build: .
    container_name: harley-ubuntu
    tty: true
    privileged: true
    ports:
      - 3306:3306
      - 5432:5432
      - 6379:6379
      - 9001:9001
      - 27017:27017
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
