[program:init]
command=/bin/bash /home/sh/init.sh
user=root
stdout_logfile=/home/logs/init.log
stderr_logfile=/home/logs/init_err.log
autostart=true
startsecs=10
stopwaitsecs=30
priority=1
autorestart=false
startretries=0